"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

export function CaptureForm({ projectId }: { projectId: string }) {
  const [label, setLabel] = useState(""); const [running, setRunning] = useState(false); const [error, setError] = useState("");
  async function run() { setError(""); setRunning(true); const supabase = createClient(); const { data: capture, error: createError } = await supabase.from("captures").insert({ project_id: projectId, label: label.trim() || null, status: "pending" }).select("id").single(); if (createError || !capture) { setError(createError?.message || "Could not create capture."); setRunning(false); return; } try { const response = await fetch("/api/capture", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ capture_id: capture.id }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Capture failed."); setLabel(""); window.location.reload(); } catch (err) { setError(err instanceof Error ? err.message : "Capture failed."); window.location.reload(); } finally { setRunning(false); } }
  return <div className="mt-7 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-navy">Run new capture</h2><p className="mt-1 text-sm text-slate-600">Screenshots are captured from every project URL.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><input value={label} onChange={(e) => setLabel(e.target.value)} placeholder="e.g. After deploy v2.3" className="min-w-0 flex-1 rounded-lg border border-slate-300 px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-brand" /><button onClick={run} disabled={running} className="rounded-lg bg-brand px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#280473] disabled:opacity-60">{running ? "Capturing…" : "Start capture"}</button></div>{error && <p role="alert" className="mt-3 text-sm text-[#8d164b]">{error}</p>}</div>;
}
