"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { UpgradeButton } from "@/components/upgrade-button";

export function SidebarNav() {
  const pathname = usePathname(); const router = useRouter(); const [account, setAccount] = useState<{ email: string; plan: "free" | "pro" } | null>(null); const match = pathname.match(/^\/projects\/([^/]+)/); const projectId = match?.[1]; const isActive = (href: string) => pathname === href ? "border-l-2 border-teal bg-teal/15" : "border-l-2 border-transparent hover:bg-white/10";
  useEffect(() => { const supabase = createClient(); supabase.auth.getUser().then(async ({ data: { user } }) => { if (!user) return; const { data: profile } = await supabase.from("profiles").select("plan").eq("id", user.id).single(); setAccount({ email: user.email || "Account", plan: profile?.plan === "pro" ? "pro" : "free" }); }); }, []);
  async function signOut() { await createClient().auth.signOut(); router.push("/login"); router.refresh(); }
  return <nav className="mt-10 flex gap-2 md:flex-col"><Link className={`rounded-r-lg px-3 py-2 text-sm font-medium ${isActive("/projects")}`} href="/projects">Projects</Link><Link className={`rounded-r-lg px-3 py-2 text-sm font-medium ${isActive("/projects/new")}`} href="/projects/new">+ New Project</Link>{projectId && projectId !== "new" && <div className="mt-5 border-t border-white/15 pt-4"><Link className="block rounded-r-lg px-3 py-2 text-sm text-slate-300 hover:bg-white/10" href="/projects">← Back to Projects</Link><Link className={`mt-1 block rounded-r-lg px-3 py-2 text-sm font-medium ${isActive(`/projects/${projectId}`)}`} href={`/projects/${projectId}`}>Captures</Link><Link className={`mt-1 block rounded-r-lg px-3 py-2 text-sm font-medium ${isActive(`/projects/${projectId}/compare`)}`} href={`/projects/${projectId}/compare`}>Compare</Link></div>}<Link className={`mt-6 rounded-r-lg px-3 py-2 text-sm text-slate-300 hover:bg-white/10 ${isActive("/landing")}`} href="/landing">About DesignQA</Link>{account && <div className="mt-8 border-t border-white/15 pt-4"><p className="truncate text-sm text-slate-300" title={account.email}>{account.email}</p><span className={`mt-2 inline-block rounded-full px-2 py-0.5 text-xs font-semibold ${account.plan === "pro" ? "bg-gradient-to-r from-brand to-pink text-white" : "bg-slate-600 text-slate-100"}`}>{account.plan === "pro" ? "Pro" : "Free"}</span>{account.plan === "free" && <div className="mt-3"><UpgradeButton>Upgrade to Pro ✦</UpgradeButton></div>}<button onClick={signOut} className="mt-4 text-sm font-medium text-slate-300 hover:text-teal">Sign out</button></div>}</nav>;
}
