import Link from "next/link";

const steps = [["1", "Add URLs", "Paste your site URLs into a project."], ["2", "Run Captures", "Capture before and after each deploy."], ["3", "Compare", "See exactly what changed visually and accessibly, with AI analysis."]];

export default function LandingPage() {
  return <main className="-m-6 bg-offwhite md:-m-10">
    <section className="bg-gradient-to-br from-navy to-brand px-6 py-20 text-white md:px-14 md:py-28"><Link href="/projects" className="text-sm font-semibold text-teal hover:underline">← Back to app</Link><div className="mx-auto mt-14 max-w-4xl"><p className="text-5xl font-bold tracking-tight md:text-7xl">Design<span className="text-teal">QA</span></p><h1 className="mt-6 text-3xl font-bold md:text-5xl">Visual &amp; Accessibility Regression Tracking</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-200">Catch what changed between deploys — screenshots, WCAG scores, and Gemini visual analysis in one report.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/signup" className="rounded-lg bg-gradient-to-r from-brand to-pink px-6 py-3 font-semibold text-white">Start Free →</Link><a href="#pricing" className="rounded-lg border border-teal px-6 py-3 font-semibold text-teal hover:bg-teal/10">See pricing</a></div></div></section>
    <section className="bg-navy px-6 py-16 md:px-10"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold text-teal">HOW IT WORKS</p><h2 className="mt-2 text-3xl font-bold text-white">Spot regressions before they ship.</h2><div className="mt-12 grid gap-6 md:grid-cols-3">{steps.map(([number, title, text]) => <div key={number} className="rounded-xl border border-teal/20 bg-white/5 p-6 text-center"><div className="mx-auto mb-4 flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-brand to-pink text-lg font-extrabold text-white">{number}</div><h3 className="font-bold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{text}</p></div>)}</div></div></section>
    <section id="pricing" className="mx-auto max-w-6xl px-6 py-16 md:px-10"><p className="text-center text-sm font-bold text-brand">SIMPLE PRICING</p><h2 className="mt-2 text-center text-3xl font-bold text-navy">Start free. Upgrade when you need more.</h2><div className="mx-auto mt-10 grid max-w-4xl gap-6 md:grid-cols-2"><PricingCard title="Free" price="$0/mo" features={["1 project", "3 URLs per project", "Unlimited captures", "WCAG reports"]} action="Get Started" href="/signup" /><PricingCard title="Pro" price="$9/mo" features={["Unlimited projects", "Unlimited URLs", "Captures", "WCAG reports", "Gemini AI analysis", "Export reports", "Email support"]} action="Start Pro" href="/signup" pro /></div></section>
    <section className="mx-auto max-w-6xl px-6 pb-16 md:px-10"><div className="rounded-xl bg-white p-8 text-center shadow-sm"><p className="text-sm font-bold text-brand">BUILT FOR</p><p className="mt-3 text-xl font-semibold text-navy">QA engineers · Design teams · Accessibility consultants · Agencies</p></div></section>
    <footer className="bg-navy px-6 py-12 text-center text-sm leading-7 text-white"><p>Built by Jerlyn O&apos;Donnell — CPACC · IAAP · Adobe Community Expert</p><p>Design Lady LLC · <a className="text-teal hover:underline" href="https://designlady.com">designlady.com</a></p><p className="mt-3 text-slate-300">Built with Gemini · Google Cloud · Build with Gemini XPRIZE 2026</p></footer>
  </main>;
}

function PricingCard({ title, price, features, action, href, pro = false }: { title: string; price: string; features: string[]; action: string; href: string; pro?: boolean }) {
  return <article className={`rounded-xl border p-7 shadow-sm ${pro ? "border-brand bg-navy text-white" : "border-slate-200 bg-white text-charcoal"}`}><h3 className="text-2xl font-bold">{title}</h3><p className={`mt-2 text-xl font-semibold ${pro ? "text-teal" : "text-brand"}`}>{price}</p><ul className="mt-6 space-y-3 text-sm">{features.map((feature) => <li key={feature}>✓ {feature}</li>)}</ul><Link href={href} className={`mt-7 inline-block rounded-lg px-4 py-2.5 text-sm font-semibold ${pro ? "bg-gradient-to-r from-brand to-pink text-white" : "border border-brand text-brand hover:bg-brand hover:text-white"}`}>{action}</Link></article>;
}
