import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

type Result = { baseline: { url: string; screenshot_url: string | null; axe_score: number | null; axe_violations: { id: string; description: string }[] | null }; comparison: { screenshot_url: string | null; axe_score: number | null; axe_violations: { id: string; description: string }[] | null } };
const escape = (value: unknown) => String(value ?? "").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character);
const score = (value: number | null) => value === null || value < 0 ? "Unavailable" : String(value);
const diff = <T extends { id: string }>(a: T[] = [], b: T[] = []) => b.filter((item) => !new Set(a.map((entry) => entry.id)).has(item.id));

export async function POST(request: NextRequest) {
  try {
    const supabase = createClient();
    const { projectId, baselineCaptureId, comparisonCaptureId, results = [] } = await request.json() as { projectId: string; baselineCaptureId: string; comparisonCaptureId: string; results: Result[] };
    if (!projectId || !baselineCaptureId || !comparisonCaptureId) return NextResponse.json({ error: "Missing report inputs." }, { status: 400 });
    const [{ data: project }, { data: captures }, { data: analyses }] = await Promise.all([supabase.from("projects").select("name").eq("id", projectId).single(), supabase.from("captures").select("id, label, created_at").in("id", [baselineCaptureId, comparisonCaptureId]), supabase.from("regression_analyses").select("url, gpt_analysis").eq("project_id", projectId).eq("baseline_capture_id", baselineCaptureId).eq("comparison_capture_id", comparisonCaptureId).order("created_at", { ascending: false })]);
    const captureById = new Map((captures ?? []).map((capture) => [capture.id, capture])); const baselineLabel = captureById.get(baselineCaptureId)?.label || "Baseline"; const comparisonLabel = captureById.get(comparisonCaptureId)?.label || "Comparison"; const analysisByUrl = new Map<string, string>(); for (const analysis of analyses ?? []) if (!analysisByUrl.has(analysis.url)) analysisByUrl.set(analysis.url, analysis.gpt_analysis);
    const counts = results.reduce((acc, row) => { const before = row.baseline.axe_score; const after = row.comparison.axe_score; if (before !== null && after !== null && before >= 0 && after >= 0) { if (after < before) acc.regressions++; if (after > before) acc.improvements++; } return acc; }, { regressions: 0, improvements: 0 });
    const sections = results.map((row) => { const beforeIssues = row.baseline.axe_violations ?? []; const afterIssues = row.comparison.axe_violations ?? []; const added = diff(beforeIssues, afterIssues); const fixed = diff(afterIssues, beforeIssues); const change = row.baseline.axe_score !== null && row.comparison.axe_score !== null ? row.comparison.axe_score - row.baseline.axe_score : null; const stored = analysisByUrl.get(row.baseline.url); let analysis = ""; try { const parsed = stored ? JSON.parse(stored) : null; if (parsed) analysis = `<div class="analysis"><strong>GPT-5.6 analysis</strong><p>${escape(parsed.summary)}</p><p><em>${escape(parsed.recommendation)}</em></p></div>`; } catch { /* stored analysis is optional */ } return `<section><h2>${escape(row.baseline.url)}</h2><div class="columns"><div><h3>${escape(baselineLabel)}</h3>${row.baseline.screenshot_url ? `<img src="${escape(row.baseline.screenshot_url)}" alt="Baseline screenshot">` : ""}<span class="score">Score: ${score(row.baseline.axe_score)}</span></div><div><h3>${escape(comparisonLabel)}</h3>${row.comparison.screenshot_url ? `<img src="${escape(row.comparison.screenshot_url)}" alt="Comparison screenshot">` : ""}<span class="score">Score: ${score(row.comparison.axe_score)}</span><p class="${change !== null && change < 0 ? "negative" : "positive"}">${change === null ? "Score unavailable" : change === 0 ? "No change" : `${change > 0 ? "▲ +" : "▼ "}${change} pts`}</p></div></div><div class="violations"><div><strong class="negative">New violations</strong><ul>${added.map((v) => `<li>${escape(v.description)}</li>`).join("") || "<li>None</li>"}</ul></div><div><strong class="positive">Fixed violations</strong><ul>${fixed.map((v) => `<li>${escape(v.description)}</li>`).join("") || "<li>None</li>"}</ul></div></div>${analysis}</section>`; }).join("");
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>DesignQA Report</title><style>body{font-family:Arial,sans-serif;color:#212529;margin:0;background:#f8f9fa}.header{padding:36px;color:white;background:linear-gradient(135deg,#36069A,#020C28)}main{max-width:1000px;margin:28px auto;padding:0 20px}.summary,.columns,.violations{display:flex;gap:20px}.summary{background:white;padding:16px;border-radius:8px}.summary span{font-weight:bold}section{background:white;padding:20px;margin:20px 0;border-radius:8px}section h2{word-break:break-all}.columns>div,.violations>div{flex:1}img{width:100%;max-height:300px;object-fit:cover;object-position:top;border-radius:6px}.score{display:block;margin-top:10px;font-weight:bold}.negative{color:#DC3545}.positive{color:#198754}.analysis{margin-top:16px;padding:12px;background:#F8F9FA;border-left:3px solid #36069A}footer{text-align:center;padding:28px;background:#020C28;color:white}footer a{color:#4ADEDE}@media(max-width:650px){.columns,.violations,.summary{display:block}.columns>div,.violations>div{margin:16px 0}}</style></head><body><header class="header"><h1>DesignQA Report</h1><p>${escape(project?.name || "Project")}</p><p>${escape(baselineLabel)} vs ${escape(comparisonLabel)} · Generated ${escape(new Date().toLocaleString())}</p></header><main><div class="summary"><p><span>${results.length}</span> URLs</p><p><span>${counts.regressions}</span> regressions</p><p><span>${counts.improvements}</span> improvements</p></div>${sections}</main><footer>Generated by DesignQA · Built by Jerlyn O'Donnell, Design Lady LLC<br><a href="https://designlady.com">designlady.com</a></footer></body></html>`;
    return new NextResponse(html, { headers: { "Content-Type": "text/html; charset=utf-8", "Content-Disposition": "attachment; filename=designqa-report.html" } });
  } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Report export failed." }, { status: 500 }); }
}
