import Link from "next/link";
import { CompareRow } from "@/components/compare-row";
import { ExportReportButton } from "@/components/export-report-button";
import { createClient } from "@/lib/supabase/server";
import type { Capture, CaptureResult, Project } from "@/lib/types";
export const dynamic = "force-dynamic";

type Props = { params: { id: string }; searchParams: { baseline?: string; comparison?: string } };
export default async function ComparePage({ params, searchParams }: Props) {
  const supabase = createClient();
  const [{ data: project }, { data: captureData }] = await Promise.all([supabase.from("projects").select("*").eq("id", params.id).single(), supabase.from("captures").select("*").eq("project_id", params.id).eq("status", "complete").order("created_at", { ascending: false })]);
  if (!project) return <section>Project not found.</section>; const item = project as Project; const captures = (captureData ?? []) as Capture[]; const baselineId = searchParams.baseline; const comparisonId = searchParams.comparison; let pairs: { baseline: CaptureResult; comparison: CaptureResult }[] = [];
  if (baselineId && comparisonId && baselineId !== comparisonId) { const [{ data: before }, { data: after }] = await Promise.all([supabase.from("capture_results").select("*").eq("capture_id", baselineId), supabase.from("capture_results").select("*").eq("capture_id", comparisonId)]); const afterByUrl = new Map(((after ?? []) as CaptureResult[]).map((result) => [result.url, result])); pairs = ((before ?? []) as CaptureResult[]).flatMap((result) => { const comparison = afterByUrl.get(result.url); return comparison ? [{ baseline: result, comparison }] : []; }); }
  const summary = pairs.reduce((counts, pair) => { if (pair.baseline.axe_score === null || pair.comparison.axe_score === null || pair.baseline.axe_score < 0 || pair.comparison.axe_score < 0 || pair.baseline.axe_score === pair.comparison.axe_score) counts.unchanged++; else if (pair.comparison.axe_score < pair.baseline.axe_score) counts.regressions++; else counts.improvements++; return counts; }, { regressions: 0, improvements: 0, unchanged: 0 });
  return <section className="mx-auto max-w-6xl"><Link href={`/projects/${item.id}`} className="text-sm font-semibold text-brand hover:underline">← {item.name}</Link><h1 className="mt-5 text-3xl font-bold text-navy">Compare captures</h1><p className="mt-2 text-slate-600">See visual and accessibility changes between two completed runs.</p><form className="mt-7 flex flex-col gap-3 rounded-xl border border-slate-200 bg-white p-5 shadow-sm md:flex-row md:items-end"><label className="flex-1 text-sm font-semibold text-charcoal">Baseline<select name="baseline" defaultValue={baselineId} className="mt-2 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 font-normal"><option value="">Select a capture</option>{captures.map((capture) => <option key={capture.id} value={capture.id}>{capture.label || "Untitled capture"} — {new Date(capture.created_at).toLocaleString()}</option>)}</select></label><label className="flex-1 text-sm font-semibold text-charcoal">Comparison<select name="comparison" defaultValue={comparisonId} className="mt-2 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 font-normal"><option value="">Select a capture</option>{captures.map((capture) => <option key={capture.id} value={capture.id}>{capture.label || "Untitled capture"} — {new Date(capture.created_at).toLocaleString()}</option>)}</select></label><button className="rounded-lg bg-brand px-5 py-2.5 text-sm font-semibold text-white hover:bg-[#280473]">Compare</button></form>{baselineId && comparisonId && baselineId === comparisonId && <p className="mt-4 text-sm text-[#b02a37]">Choose two different captures.</p>}{pairs.length > 0 && <><div className="mt-8 grid gap-3 rounded-xl bg-navy p-4 text-white sm:grid-cols-4"><p><strong>{pairs.length}</strong> URLs compared</p><p className="text-pink"><strong>{summary.regressions}</strong> regressions</p><p className="text-teal"><strong>{summary.improvements}</strong> improvements</p><p><strong>{summary.unchanged}</strong> unchanged</p></div><ExportReportButton projectId={item.id} baselineCaptureId={baselineId!} comparisonCaptureId={comparisonId!} results={pairs} /><div className="mt-5 space-y-5">{pairs.map((pair) => <CompareRow key={pair.baseline.url_id} {...pair} projectId={item.id} baselineCaptureId={baselineId!} comparisonCaptureId={comparisonId!} />)}</div></>}{baselineId && comparisonId && baselineId !== comparisonId && pairs.length === 0 && <p className="mt-8 rounded-xl border border-dashed border-slate-300 bg-white p-8 text-sm text-slate-600">No matching URLs were found in these captures.</p>}</section>;
}
